### ISSUE TITLE
start_time_entry seems to be broken

### ISSUE THREAD

**Issue by bartoszkopinski** [wkang/toggl_api#1]
Starting new time entry tends to throw "undefined method bytesize for Hash" from Faraday (data body should be a string). Is this my fault or not finished feature?

**Comment by wkang** [comment]
Fix it e71128d4bf3e167165843d748739cb7e22972269.
not adding Faraday : url_encoded, sorry!

**Comment by bartoszkopinski** [comment]
Cheers, looks like it's working now. 
Thanks for the gem.
